#================configs related to carbon.xml=============
[server]
hostname = "obiam"
node_ip = "127.0.0.1"
base_path = "https://$ref{server.hostname}:${carbon.management.port}"
serverDetails = "WSO2 IS as KM 5.10.0"
mode = "single"
userAgent = "WSO2 IS as KM 5.10.0"
offset = 3

[keystore.primary]
name = "wso2carbon.jks"
password = "wso2carbon"

[tenant_mgt]
enable_email_domain = true

#================configs related to user-mgt.xml=============

[super_admin]
username = "admin@wso2.com"
password = "wso2123"
create_admin_account = true

[realm_manager]
data_source= "WSO2UM_DB"

[user_store]
type = "database_unique_id"
class = "org.wso2.carbon.user.core.jdbc.UniqueIDJDBCUserStoreManager"

[user_store.properties]
UsernameJavaRegEx = "a-zA-Z0-9@._-{3,30}$"
UsernameJavaScriptRegEx = "^[a-zA-Z0-9._-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,4}$"
SCIMEnabled = false
IsBulkImportSupported = false
LeadingOrTrailingSpaceAllowedInUserName = false
UsernameWithEmailJavaScriptRegEx = "^[\\S]{3,30}$"

[authorization_manager]
class = "org.wso2.carbon.user.core.authorization.JDBCAuthorizationManager"

[authorization_manager.properties]
AdminRoleManagementPermissions = "/permission"
AuthorizationCacheEnabled = true
GetAllRolesOfUserEnabled = false

#================configs related to master-datasources.xml=============

# for registry data
[database.shared_db]
url = "jdbc:mysql://mysql:3306/openbank_govdb?autoReconnect=true&amp;useSSL=false"
username = "root"
password = "root"
driver = "com.mysql.jdbc.Driver"

[database.shared_db.pool_options]
maxActive = "150"
maxWait = "60000"
minIdle ="5"
testOnBorrow = true
validationQuery="SELECT 1"
#Use below for oracle
#validationQuery="SELECT 1 FROM DUAL"
validationInterval="30000"
defaultAutoCommit=false

# for api manager data
[database.apim_db]
url = "jdbc:mysql://mysql:3306/openbank_apimgtdb?autoReconnect=true&amp;useSSL=false"
username = "root"
password = "root"
driver = "com.mysql.jdbc.Driver"

[database.apim_db.pool_options]
maxActive = "150"
maxWait = "60000"
minIdle ="5"
testOnBorrow = true
validationQuery="SELECT 1"
#Use below for oracle
#validationQuery="SELECT 1 FROM DUAL"
validationInterval="30000"
defaultAutoCommit=false

# for km-config registry
[database.config]
url = "jdbc:mysql://mysql:3306/openbank_iskm_configdb?autoReconnect=true&amp;useSSL=false"
username = "root"
password = "root"
driver = "com.mysql.jdbc.Driver"

[database.config.pool_options]
maxActive = "150"
maxWait = "60000"
minIdle ="5"
testOnBorrow = true
validationQuery="SELECT 1"
#Use below for oracle
#validationQuery="SELECT 1 FROM DUAL"
validationInterval="30000"
defaultAutoCommit=false

# for user management data
[[datasource]]
id="WSO2UM_DB"
url = "jdbc:mysql://mysql:3306/openbank_userdb?autoReconnect=true&amp;useSSL=false"
username = "root"
password = "root"
driver = "com.mysql.jdbc.Driver"
jmx_enable=false
pool_options.maxActive = "150"
pool_options.maxWait = "60000"
pool_options.minIdle = "5"
pool_options.testOnBorrow = true
pool_options.validationQuery="SELECT 1"
#Use below for oracle
#validationQuery="SELECT 1 FROM DUAL"
pool_options.validationInterval="30000"
pool_options.defaultAutoCommit=false

#================configs related to application-authentication.xml=============

[authentication.endpoints]
login_url = "https://obiam:9446/authenticationendpoint/login.do"
retry_url = "https://obiam:9446/authenticationendpoint/retry.do"

[authentication.endpoint.redirect_params]
filter_policy = "include"
remove_on_consume_from_api = "true"
parameters = ["sessionDataKeyConsent","relyingParty", "authenticators", "authFailureMsg", "authFailure"]

[authentication.authenticator.sms_otp.parameters]
SMSOTPAuthenticationEndpointURL = "authenticationendpoint/smsotp.jsp"
EnableAccountLockingForFailedAttempts = true
BackupCode = false
TokenExpiryTime = 60

[[authentication.custom_authenticator]]
name = "OBIdentifierExecutor"
parameters.ValidateUsername = true
parameters.throttleLimit = 4
parameters.throttleTimePeriod = 300
parameters.authRequestURL= "https://obiam:9446/api/identity/auth/v1.1/data/AuthRequestKey/"

#================configs related to api-manager.xml=============

[[apim.gateway.environment]]
name = "Production and Sandbox"
type = "hybrid"
display_in_api_console = true
description = "This is a hybrid gateway that handles both production and sandbox token traffic."
service_url = "https://obam:9443/services/"
username= "${admin.username}"
password= "${admin.password}"
https_endpoint = "https://${carbon.local.ip}:${https.nio.port}"
http_endpoint = "http://${carbon.local.ip}:${http.nio.port}"
ws_endpoint = "ws://${carbon.local.ip}:9099"

[apim.oauth_config]
white_listed_scopes = ["^device_.*","openid","extended_transaction_history", "^OB_.*", "^TIME_.*", "^x5t.*"]

[apim.jwt]
enable = false
signing_algorithm = "NONE"
header = "X-JWT-Assertion"

[apim.throttling]
enable_data_publishing = false
enable_policy_deploy = true
enable_blacklist_condition = true
enable_decision_connection = true

[apim.jwt_authenitcation]
subscription_validation_via_km = false

[[apim.devportal.application_attributes]]
required = true
hidden = false
name ="Regulatory Compliance"
description = "Regulatory Compliance"


#================configs related to identity.xml=============

[identity_data_source]
skip_db_schema_creation = true

[oauth.endpoints]
oauth2_authz_url = "${carbon.protocol}://obam:8243/authorize"
oauth2_token_url = "${carbon.protocol}://obam:8243/token"
oauth2_user_info_url = "${carbon.protocol}://obam:8243/userinfo"
oauth2_consent_page = "${carbon.protocol}://obiam:${carbon.management.port}/ob/authenticationendpoint/oauth2_authz.do"
oidc_consent_page = "${carbon.protocol}://obiam:${carbon.management.port}/ob/authenticationendpoint/oauth2_consent.do"
oauth2_dcr_url = "${carbon.protocol}://obam:8243/open-banking/0.1/register"

[oauth.token_renewal]
renew_refresh_token = false

[oauth.response_type]
token.enable = true
code.enable = false
id_token.enable = true
id_token_token.enable = false
device.enable = true

[[oauth.custom_response_type]]
name = "code"
class = "com.wso2.finance.open.banking.identity.extensions.response.type.handlers.OBCodeResponseTypeHandler"
validator = "com.wso2.finance.open.banking.identity.extensions.response.type.validators.OBCodeTokenResponseValidator"

[[oauth.custom_response_type]]
name = "code id_token"
class = "com.wso2.finance.open.banking.identity.extensions.response.type.handlers.OBHybridResponseTypeHandler"

[oauth.grant_type]
authorization_code.enable = true
authorization_code.grant_handler = "com.wso2.finance.open.banking.identity.extensions.grant.type.handlers.OBAuthorizationCodeGrantHandler"
refresh_token.enable = true
refresh_token.grant_handler = "com.wso2.finance.open.banking.identity.extensions.grant.type.handlers.OBRefreshGrantHandler"
client_credentials.enable = true
client_credentials.grant_handler = "com.wso2.finance.open.banking.identity.extensions.grant.type.handlers.OBClientCredentialsGrantHandler"
iwa_ntlm.enable = false
jwt_bearer.enable = false

[oauth.grant_type.uma_ticket]
retrieve_uma_permission_info_through_introspection="true"

[oauth.oidc]
extensions.id_token_builder = "com.wso2.finance.open.banking.idtoken.builder.OBIDTokenBuilder"
id_token.issuer = "https://obam:8243/token"
id_token.sign_before_encryption = true
extensions.request_object_validator = "com.wso2.finance.open.banking.request.object.validator.OBRequestObjectValidatorImpl"

[identity_mgt.user_self_registration]
allow_self_registration = true

[[event_listener]]
id = "mutual_tls_authenticator"
type = "org.wso2.carbon.identity.core.handler.AbstractIdentityHandler"
name = "org.wso2.carbon.identity.oauth2.token.handler.clientauth.mutualtls.MutualTLSClientAuthenticator"
order = "158"
enable = false

[[event_listener]]
id = "ob_mutual_tls_authenticator"
type = "org.wso2.carbon.identity.core.handler.AbstractIdentityHandler"
name = "com.wso2.finance.open.banking.mtls.authenticator.OBMutualTLSClientAuthenticator"
order = "26"
enable = false

[[event_listener]]
id = "private_key_jwt_authenticator"
type = "org.wso2.carbon.identity.core.handler.AbstractIdentityHandler"
name = "org.wso2.carbon.identity.oauth2.token.handler.clientauth.jwt.PrivateKeyJWTClientAuthenticator"
order = "899"
enable = false

[[event_listener]]
id = "au_token_private_key_jwt_authenticator"
type = "org.wso2.carbon.identity.core.handler.AbstractIdentityHandler"
name = "com.wso2.finance.open.banking.identity.extensions.clientauthenticators.au.AUTokenPrivateKeyJWTAuthenticator"
order = "-10"
enable = true

[event_listener.properties]
TokenEndpointAlias = "https://obam:8243/token"

[[event_listener]]
id = "au_revocation_private_key_jwt_authenticator"
type = "org.wso2.carbon.identity.core.handler.AbstractIdentityHandler"
name = "com.wso2.finance.open.banking.identity.extensions.clientauthenticators.au.AURevocationPrivateKeyJWTAuthenticator"
order = "-11"
enable = true

[event_listener.properties]
TokenEndpointAlias = "https://obam:8243/token"

[[event_listener]]
id = "au_introspection_private_key_jwt_authenticator"
type = "org.wso2.carbon.identity.core.handler.AbstractIdentityHandler"
name = "com.wso2.finance.open.banking.identity.extensions.clientauthenticators.au.AUIntorspectionPrivateKeyJWTAuthenticator"
order = "-12"
enable = true

[event_listener.properties]
TokenEndpointAlias = "https://localhost:8243/token"

[[event_listener]]
id = "au_arrangement_revocation_private_key_jwt_authenticator"
type = "org.wso2.carbon.identity.core.handler.AbstractIdentityHandler"
name = "com.wso2.finance.open.banking.identity.extensions.clientauthenticators.au.AUArrangementPrivateKeyJWTAuthenticator"
order = "-13"
enable = true

[event_listener.properties]
TokenEndpointAlias = "https://obam:8243/arrangements/1.0.0"

[[event_listener]]
id = "ob_introspection_response_interceptor"
type = "org.wso2.carbon.identity.core.handler.AbstractIdentityHandler"
name = "com.wso2.finance.open.banking.identity.extensions.introspection.OBIntrospectionResponseInterceptor"
order = "27"
enable = true

[[event_listener]]
id = "ob_introspection_data_provider"
type = "org.wso2.carbon.identity.core.handler.AbstractIdentityHandler"
name = "com.wso2.finance.open.banking.identity.extensions.introspection.OBIntrospectionDataProvider"
order = "28"
enable = true

[[event_listener]]
id = "ob_token_revocation_listener"
type = "org.wso2.carbon.identity.core.handler.AbstractIdentityHandler"
name = "com.wso2.finance.open.banking.identity.extensions.listeners.TokenRevocationListener"
order = "100"
enable = true

[resource_access_control]
default_access_allow= true

[[resource.access_control]]
context = "(.*)/berlin110/(.*)"
secure="true"
http_method="all"
permissions=["/permission/admin"]

[[resource.access_control]]
context = "(.*)/berlin130/(.*)"
secure="true"
http_method="all"
permissions=["/permission/admin"]

[[resource.access_control]]
context = "(.*)/stet140/(.*)"
secure="true"
http_method="all"
permissions=["/permission/admin"]

[[resource.access_control]]
context = "(.*)/uk110/(.*)"
secure="true"
http_method="all"
permissions=["/permission/admin"]

[[resource.access_control]]
context = "(.*)/uk200/(.*)"
secure="true"
http_method="all"
permissions=["/permission/admin"]

[[resource.access_control]]
context = "(.*)/uk300/(.*)"
secure="true"
http_method="all"
permissions=["/permission/admin"]

[authentication.adaptive.event_publisher]
url = "http://localhost:8006/"

[[oauth.oidc.custom_request_object_builder]]
type = "request_uri_param_value_builder"
class = "com.wso2.finance.open.banking.identity.extensions.builders.RequestUriRequestObjectBuilder"

#================configs related to identity-event.properties=============

[[event_handler]]
name="userPostSelfRegistration"
subscriptions=["POST_ADD_USER"]

#================configs related to open-banking-datasources.xml=============

[open_banking_database]
config.url = "jdbc:mysql://mysql:3306/openbank_openbankingdb?autoReconnect=true&amp;useSSL=false"
config.username = "root"
config.password = "root"
config.driver = "com.mysql.jdbc.Driver"

[open_banking_database.config.pool_options]
maxActive = "150"
maxWait = "60000"
minIdle ="5"
testOnBorrow = true
validationQuery="SELECT 1"
#Use below for oracle
#validationQuery="SELECT 1 FROM DUAL"
validationInterval="30000"
defaultAutoCommit=false

#================custom filters and filter-mappings==============
[[tomcat.filter]]
name = "TokenFilter"
class = "com.wso2.finance.open.banking.identity.extensions.filter.TokenFilter"

[[tomcat.filter]]
name = "MTLSEnforcementFilter"
class = "com.wso2.finance.open.banking.identity.extensions.filter.MTLSEnforcementFilter"

[[tomcat.filter]]
name = "PrivateKeyJwtAuthenticationFilter"
class = "com.wso2.finance.open.banking.identity.extensions.filter.PrivateKeyJwtAuthenticationFilter"

[[tomcat.filter_mapping]]
name = "TokenFilter"
url_pattern = "/token/*"

[[tomcat.filter_mapping]]
name = "TokenFilter"
url_pattern = "/arrangements/*"

[[tomcat.filter_mapping]]
name = "PrivateKeyJwtAuthenticationFilter"
url_pattern = "/arrangements/*"

[[tomcat.filter_mapping]]
name = "TokenFilter"
url_pattern = "/revoke/*"

[[tomcat.filter_mapping]]
name = "MTLSEnforcementFilter"
url_pattern = "/introspect/*"

[[tomcat.filter_mapping]]
name = "PrivateKeyJwtAuthenticationFilter"
url_pattern = "/introspect/*"

[[tomcat.filter_mapping]]
name = "MTLSEnforcementFilter"
url_pattern = "/userinfo/*"

[[tomcat.filter_mapping]]
name = "MTLSEnforcementFilter"
url_pattern = "/par/*"

#================configs related to open-banking.xml=============

[open_banking]
deployed_spec = "AU"
payable_accounts_retrieve_endpoint = "http://obam:9763/api/openbanking/backend-uk/services/bankaccounts/bankaccountservice/payable-accounts"
sharable_accounts_retrieve_endpoint = "http://obam:9763/api/openbanking/backend-uk/services/bankaccounts/bankaccountservice/sharable-accounts"

[open_banking.jdbc_persistence_manager.data_source]
name= "WSO2OpenBankingDB"

[open_banking.au]
holder_identifier = "wso2"

[open_banking.au.metadata_cache]
enable = false
update_period = 1
default_timeout = 1
dcr_internal_url = "https://obam:9443/api/openbanking/dynamic-client-registration/common/register/"
data_recipient_discovery_url = "http://localhost:3000/dr"
software_product_discovery_url = "http://localhost:3000/sp"
token_revocation_url = "https://obam:9443/oauth2/revoke"

[open_banking.dcr]
uri_validation.enable = false
hostname_validation.enable = false
software_id_as_application_name.enable = true

[open_banking.api_security]
mtls_token_binding.enable = true

[open_banking.api_security.global]
username = "$ref{super_admin.username}"
password = "$ref{super_admin.password}"

[open_banking.cert_mgt]
client_auth_header = "x-wso2-mutual-auth-cert"

[open_banking.cert_mgt.cert_revocation_proxy]
enable = false
proxy_host = "PROXY_HOSTNAME"
proxy_port = "8080"

[open_banking.bi_server]
username = "$ref{super_admin.username}@carbon.super"
password = "$ref{super_admin.password}"

[open_banking.bi_server.data_publishing]
enable = true
server_url = "{tcp://obbi-worker:7612}"

[open_banking.bi_server.tra]
enable = false
payment_validation.enable = false
account_validation.enable = false

[open_banking.bi_server.tra.receivers]
account_validation_url = "http://obbi-worker:8007/TRAAccountValidationApp/TRAValidationStream"
payment_validation_url = "http://obbi-worker:8007/TRAPaymentValidationApp/TRAValidationStream"

[open_banking.bi_server.fraud_detection]
enable = false

[open_banking.bi_server.fraud_detection.receivers]
fraud_detection_url = "http://obbi-worker:8007/FraudDetectionApp/FraudDetectionStream"
invalid_submission_url = "http://obbi-worker:8006/InvalidSubmissionsApp/InvalidSubmissionsStream"

[open_banking.account_id_validation_on_retrieval]
enable = true

[[open_banking.authorize.steps.persist.step]]
class="com.wso2.finance.open.banking.consent.authorize.steps.impl.steps.persist.JointAccountConsentPersistenceStep"
priority=5

[open_banking.au.customer.details]
enable = false
# {userID} will replace the customer ID
url = "https://obam:9443/api/openbanking/backend-cds/services/customerdetails/details/{userId}"

[open_banking.au.account.masking]
enable = false
