# ----------------------------------------------------------------------------------------
#
# Copyright (c) 2025, WSO2 LLC. (https://www.wso2.com). All Rights Reserved.
#
# This software is the property of WSO2 LLC. and its suppliers, if any.
# Dissemination of any information or reproduction of any material contained
# herein in any form is strictly forbidden, unless permitted by WSO2 expressly.
# You may not alter or remove any copyright or other notice from copies of this content.
#
# ----------------------------------------------------------------------------------------

version: "3.7"
services:
  
  mysql:
    container_name: mysql
    image: mysql:8.0.32
    ports:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - "../mysql/scripts/permission.sql:/docker-entrypoint-initdb.d/permission.sql"
      - "../mysql/scripts/setup-IS-7.1.0.sql:/docker-entrypoint-initdb.d/setup.sql"
      - "../mysql/conf:/etc/mysql/conf.d"
    ulimits:
      nofile:
        soft: 20000
        hard: 40000
    command: [--ssl=0]
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-uroot", "-proot"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s
    networks:
      - fs-network

  fsiam:
    container_name: fsiam
    image: docker.wso2.com/wso2-fsiam:4.0.0.0-is7.1.0.0
    healthcheck:
      test: ["CMD", "curl", "-k", "-f", "https://fsiam:9446/console"]
      interval: 10s
      timeout: 120s
      start_period: 100s
      retries: 5 
    depends_on:
      - "mysql"
    volumes:
      - "./wait-for-it.sh:/home/wso2carbon/wait-for-it.sh"
    ports:
      - "9446:9446"
    entrypoint:
      - "/home/wso2carbon/wait-for-it.sh"
      - "mysql:3306"
      - "-t"
      - "200"
      - "--"
      - "./docker-entrypoint.sh"
    networks:
      - fs-network

  am:
    container_name: fsam
    image: docker.wso2.com/wso2-fsam:4.0.0.0-am4.5.0.0
    healthcheck:
      test: ["CMD", "curl", "-k", "-f", "https://fsam:9443/carbon/admin/login.jsp"]
      interval: 10s
      timeout: 10s
      start_period: 150s
      retries: 5 
    depends_on:
      - "mysql"
      - "fsiam"
    volumes:
      - "./wait-for-it.sh:/home/wso2carbon/wait-for-it.sh"
    ports:
      - "9443:9443"
      - "8243:8243"
      - "8280:8280"
    entrypoint:
      - "/home/wso2carbon/wait-for-it.sh"
      - "fsiam:9446"
      - "-t"
      - "300"
      - "--"
      - "./docker-entrypoint.sh"
    networks:
      - fs-network

networks:
  fs-network:
    driver: bridge
    name: fs-network
